spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.230.240.26:3306/remote_mooc?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: mooc
    password: mooc
  freemarker:
    cache: false
    check-template-location: true
    suffix: .ftl  #文件后缀
    charset: utf-8
    settings:
      classic_compatible: true
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**

logging:
        config: src/main/resources/logback-spring.xml

